export type InstrumentKind = "index" | "etf" | "stock";

export type Instrument = {
  symbol: string;
  name: string;
  kind: InstrumentKind;
  sector: string;
  start: number;
  vol: number;
  beta: number;
  lot: number;
  weight: number;
  pointValue: number;
  maxLeverage: number;
};

export const STARTING_CASH = 10_000;
export const GOAL_EQUITY = 100_000_000;
export const HSI_SYMBOL = "HSI";

export const UNIVERSE: Instrument[] = [
  {
    symbol: "HSI",
    name: "恒生指數迷你",
    kind: "index",
    sector: "指數",
    start: 25842,
    vol: 0.012,
    beta: 1,
    lot: 1,
    weight: 0,
    pointValue: 1,
    maxLeverage: 10,
  },
  {
    symbol: "2800",
    name: "盈富基金",
    kind: "etf",
    sector: "指數",
    start: 25.84,
    vol: 0.01,
    beta: 1,
    lot: 100,
    weight: 0,
    pointValue: 1,
    maxLeverage: 1,
  },
  {
    symbol: "0005",
    name: "匯豐控股",
    kind: "stock",
    sector: "金融",
    start: 88.45,
    vol: 0.011,
    beta: 0.85,
    lot: 400,
    weight: 0.09,
    pointValue: 1,
    maxLeverage: 5,
  },
  {
    symbol: "0700",
    name: "騰訊控股",
    kind: "stock",
    sector: "科技",
    start: 412.6,
    vol: 0.018,
    beta: 1.25,
    lot: 100,
    weight: 0.11,
    pointValue: 1,
    maxLeverage: 5,
  },
  {
    symbol: "9988",
    name: "阿里巴巴",
    kind: "stock",
    sector: "科技",
    start: 92.15,
    vol: 0.02,
    beta: 1.3,
    lot: 100,
    weight: 0.07,
    pointValue: 1,
    maxLeverage: 5,
  },
  {
    symbol: "3690",
    name: "美團",
    kind: "stock",
    sector: "科技",
    start: 118.3,
    vol: 0.024,
    beta: 1.35,
    lot: 100,
    weight: 0.05,
    pointValue: 1,
    maxLeverage: 5,
  },
  {
    symbol: "1810",
    name: "小米集團",
    kind: "stock",
    sector: "科技",
    start: 48.75,
    vol: 0.026,
    beta: 1.4,
    lot: 200,
    weight: 0.045,
    pointValue: 1,
    maxLeverage: 5,
  },
  {
    symbol: "0941",
    name: "中國移動",
    kind: "stock",
    sector: "電訊",
    start: 76.2,
    vol: 0.009,
    beta: 0.55,
    lot: 500,
    weight: 0.07,
    pointValue: 1,
    maxLeverage: 2,
  },
  {
    symbol: "1299",
    name: "友邦保險",
    kind: "stock",
    sector: "金融",
    start: 68.9,
    vol: 0.013,
    beta: 0.9,
    lot: 200,
    weight: 0.08,
    pointValue: 1,
    maxLeverage: 5,
  },
  {
    symbol: "0388",
    name: "港交所",
    kind: "stock",
    sector: "金融",
    start: 352.4,
    vol: 0.016,
    beta: 1.1,
    lot: 100,
    weight: 0.06,
    pointValue: 1,
    maxLeverage: 5,
  },
  {
    symbol: "2318",
    name: "中國平安",
    kind: "stock",
    sector: "金融",
    start: 47.85,
    vol: 0.017,
    beta: 1.05,
    lot: 500,
    weight: 0.05,
    pointValue: 1,
    maxLeverage: 5,
  },
  {
    symbol: "1211",
    name: "比亞迪股份",
    kind: "stock",
    sector: "汽車",
    start: 268,
    vol: 0.022,
    beta: 1.2,
    lot: 50,
    weight: 0.04,
    pointValue: 1,
    maxLeverage: 5,
  },
  {
    symbol: "9618",
    name: "京東集團",
    kind: "stock",
    sector: "科技",
    start: 128.5,
    vol: 0.023,
    beta: 1.28,
    lot: 50,
    weight: 0.03,
    pointValue: 1,
    maxLeverage: 5,
  },
  {
    symbol: "9999",
    name: "網易",
    kind: "stock",
    sector: "科技",
    start: 154.8,
    vol: 0.019,
    beta: 1.15,
    lot: 100,
    weight: 0.025,
    pointValue: 1,
    maxLeverage: 5,
  },
  {
    symbol: "0001",
    name: "長和",
    kind: "stock",
    sector: "地產",
    start: 46.2,
    vol: 0.012,
    beta: 0.7,
    lot: 500,
    weight: 0.03,
    pointValue: 1,
    maxLeverage: 2,
  },
  {
    symbol: "0002",
    name: "中電控股",
    kind: "stock",
    sector: "公用",
    start: 64.75,
    vol: 0.007,
    beta: 0.35,
    lot: 500,
    weight: 0.025,
    pointValue: 1,
    maxLeverage: 2,
  },
  {
    symbol: "0011",
    name: "恒生銀行",
    kind: "stock",
    sector: "金融",
    start: 108.3,
    vol: 0.01,
    beta: 0.65,
    lot: 100,
    weight: 0.03,
    pointValue: 1,
    maxLeverage: 2,
  },
  {
    symbol: "0175",
    name: "吉利汽車",
    kind: "stock",
    sector: "汽車",
    start: 16.42,
    vol: 0.025,
    beta: 1.22,
    lot: 500,
    weight: 0.02,
    pointValue: 1,
    maxLeverage: 5,
  },
  {
    symbol: "2020",
    name: "安踏體育",
    kind: "stock",
    sector: "消費",
    start: 86.5,
    vol: 0.018,
    beta: 0.95,
    lot: 200,
    weight: 0.02,
    pointValue: 1,
    maxLeverage: 5,
  },
  {
    symbol: "2382",
    name: "舜宇光學",
    kind: "stock",
    sector: "科技",
    start: 62.8,
    vol: 0.028,
    beta: 1.32,
    lot: 100,
    weight: 0.015,
    pointValue: 1,
    maxLeverage: 5,
  },
  {
    symbol: "1024",
    name: "快手",
    kind: "stock",
    sector: "科技",
    start: 52.4,
    vol: 0.03,
    beta: 1.45,
    lot: 100,
    weight: 0.02,
    pointValue: 1,
    maxLeverage: 5,
  },
  {
    symbol: "9961",
    name: "攜程集團",
    kind: "stock",
    sector: "消費",
    start: 478,
    vol: 0.021,
    beta: 1.18,
    lot: 50,
    weight: 0.02,
    pointValue: 1,
    maxLeverage: 5,
  },
  {
    symbol: "9888",
    name: "百度集團",
    kind: "stock",
    sector: "科技",
    start: 91.2,
    vol: 0.022,
    beta: 1.2,
    lot: 50,
    weight: 0.02,
    pointValue: 1,
    maxLeverage: 5,
  },
  {
    symbol: "0434",
    name: "博雅互動",
    kind: "stock",
    sector: "科技",
    start: 5.18,
    vol: 0.038,
    beta: 1.15,
    lot: 400,
    weight: 0,
    pointValue: 1,
    maxLeverage: 5,
  },
  {
    symbol: "3988",
    name: "中國銀行",
    kind: "stock",
    sector: "金融",
    start: 4.21,
    vol: 0.01,
    beta: 0.72,
    lot: 1000,
    weight: 0.04,
    pointValue: 1,
    maxLeverage: 2,
  },
];

export const BY_SYMBOL = Object.fromEntries(UNIVERSE.map((i) => [i.symbol, i]));

export function tickSize(price: number): number {
  if (price < 0.25) return 0.001;
  if (price < 0.5) return 0.005;
  if (price < 10) return 0.01;
  if (price < 20) return 0.02;
  if (price < 50) return 0.05;
  if (price < 100) return 0.1;
  if (price < 200) return 0.2;
  if (price < 500) return 0.5;
  if (price < 1000) return 1;
  if (price < 2000) return 2;
  if (price < 5000) return 5;
  return 10;
}

export function roundTick(price: number): number {
  const t = tickSize(price);
  return Math.max(t, Math.round(price / t) * t);
}

export const NEWS_POOL: { text: string; bias: number; focus?: string }[] = [
  { text: "北水持續淨流入，港股氣氛轉旺", bias: 0.45 },
  { text: "聯儲局官員放鴿，資金重新追逐風險資產", bias: 0.55 },
  { text: "內地公布消費補貼細節，零售與互聯網受捧", bias: 0.4, focus: "3690" },
  { text: "騰訊遊戲版號獲批，科技股急彈", bias: 0.7, focus: "0700" },
  { text: "阿里雲簽下大型企業合約，電商板塊跟漲", bias: 0.5, focus: "9988" },
  { text: "小米新機預售超預期，硬件股活躍", bias: 0.6, focus: "1810" },
  { text: "港交所成交額創月內新高", bias: 0.35, focus: "0388" },
  { text: "匯豐上調亞洲業務指引", bias: 0.4, focus: "0005" },
  { text: "友邦新業務價值勝預期", bias: 0.35, focus: "1299" },
  { text: "比亞迪海外銷量再創新高", bias: 0.5, focus: "1211" },
  { text: "地緣風險升溫，資金湧入防守股", bias: -0.35 },
  { text: "港元拆息抽升，金融股受壓", bias: -0.4, focus: "0005" },
  { text: "監管傳聞再起，科網股高位回吐", bias: -0.55 },
  { text: "美團即時零售競爭加劇，市場憂慮利潤率", bias: -0.45, focus: "3690" },
  { text: "內地樓市數據遜預期，地產相關受挫", bias: -0.4, focus: "0001" },
  { text: "油價急升推高通脹預期，風險胃納下降", bias: -0.3 },
  { text: "快手廣告收入指引保守", bias: -0.4, focus: "1024" },
  { text: "舜宇光學大客戶訂單下修", bias: -0.5, focus: "2382" },
  { text: "中國移動派息政策維持進取", bias: 0.25, focus: "0941" },
  { text: "攜程暑假預訂數據強勁", bias: 0.45, focus: "9961" },
  { text: "博雅互動海外棋牌流水回升，股份交投轉旺", bias: 0.55, focus: "0434" },
  { text: "中國銀行息差穩定，派息率維持進取", bias: 0.3, focus: "3988" },
];
